
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Serhiy Ushchapivskyy
 */
public class HelpSoftware extends javax.swing.JPanel {

    Helper fe = new Helper();
    public String[] capsule = fe.getCapsuleName();
    public String[] numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};

    /**
     * Creates new form HelpSoftware
     */
    public HelpSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jtfNome = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        bAccedi = new javax.swing.JButton();
        lNome = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 14;
        add(jtfNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 14;
        add(jpfPassword, gridBagConstraints);

        bAccedi.setText("Accedi");
        bAccedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccediActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 14;
        add(bAccedi, gridBagConstraints);

        lNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNome.setText("Nome");
        lNome.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 174;
        add(lNome, gridBagConstraints);

        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 174;
        add(lPassword, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bAccediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccediActionPerformed
        String nome = jtfNome.getText();
        String password = new String(jpfPassword.getPassword());
        if (fe.connected(nome, password)) {
            JFrame frame = new JFrame("Input Dialog Example 3");
            String favoritePizza = (String) JOptionPane.showInputDialog(frame,
                    "Scegli la capsula",
                    "Capsula:",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    capsule,
                    capsule[0]);
            String pizzaNumber = (String) JOptionPane.showInputDialog(frame,
                    "Scegli il numero",
                    "Favorite Pizza",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    numbers,
                    numbers[0]);
            System.out.println("You want " + pizzaNumber + " of " + favoritePizza);
            System.exit(0);
        }
    }//GEN-LAST:event_bAccediActionPerformed

    public static void main(String[] args) {
        JFrame jf = new JFrame("HelpSoftware");
        HelpSoftware tc = new HelpSoftware();
        //(new Thread(tc)).start();
        jf.add(tc);
        jf.pack();
        jf.setVisible(true);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setResizable(false);

        String password2 = "utente0";

        MessageDigest md;
        try {
            md = MessageDigest.getInstance("SHA-256");
            md.update(password2.getBytes());
            byte byteData[] = md.digest();

            //convert the byte to hex format method 1
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < byteData.length; i++) {
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }

            System.out.println("Hex format : " + sb.toString());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(HelpSoftware.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccedi;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPassword;
    // End of variables declaration//GEN-END:variables
}
