insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tanjay', 'Vyšší Brod', '2015-04-21', 'Wulingyuan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Rizal', 'Atafu Village', '2015-09-28', 'Taipa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Duanshen', 'Panayagan', '2015-02-10', 'Saint-Denis');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shuangchahe', 'Fenghuangdong', '2015-07-15', 'Tianxin');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chalu', 'Huddinge', '2015-05-10', 'Matwaḩ');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wolowiro', 'Zghartā', '2015-11-29', 'Ōmiya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Taoling', 'Nyūzen', '2016-01-30', 'Topolovgrad');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Frösön', 'Bussum', '2015-09-16', 'Arnaía');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Suklayin', 'San Pedro Zacapa', '2015-05-31', 'Międzybrodzie Bialskie');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Oktyabr’sk', 'Yumaguzino', '2015-07-09', 'Lučina');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Toulon', 'Montargis', '2016-01-20', 'Oslo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Butare', 'Siemiatycze', '2015-03-29', 'Mamasa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kinango', 'Binzhou', '2015-12-17', 'Catende');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mingoyo', 'Songwon', '2015-03-28', 'Mulan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lingkou', 'Murça', '2015-09-12', 'Mujur Satu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Irvine', 'Anliang', '2015-11-29', 'Dolna Banya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Conceição da Feira', 'San Carlos', '2015-12-07', 'Xinfeng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kalipucang', 'Daming', '2015-03-17', 'Al Bayḑā’');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Aguadas', 'Des Moines', '2015-07-30', 'Montréal-Ouest');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Huangbizhuang', 'Cotabambas', '2015-09-07', 'Sumy');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yezhi', 'Krajan Gebangan', '2015-07-06', 'Tarumizu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bayt ‘Ūr at Taḩtā', 'Long Xuyên', '2015-11-15', 'Zbůch');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Funchal', 'Donghe', '2015-08-17', 'Kroonstad');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Qiaolin', 'Jönköping', '2015-05-20', 'Tulung');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hengduo', 'Shuangxi', '2015-11-24', 'Notodden');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kelburn', 'Brest', '2015-03-06', 'Marondera');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Werangere', 'Sérvia', '2015-12-20', 'Tyarlevo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nungwi', 'Jianrao', '2016-01-17', 'Santa Maria da Vitória');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tocopilla', 'Maliang', '2015-04-19', 'At-Bashi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Socorro', 'Caen', '2015-09-19', 'Itumbiara');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Vila Real de Santo António', 'Kuala Lumpur', '2015-12-23', 'Hartford');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jakubów', 'Blendis', '2015-12-21', 'Lautaro');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Irbit', 'Yangjiapo', '2016-01-01', 'Aourir');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gitega', 'Kaiama', '2015-08-01', 'Kupino');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nastola', 'Huji', '2015-04-26', 'Babakan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Beicheng', 'Hövsan', '2015-07-20', 'Shuikou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pacaraos', 'Korostyshiv', '2015-08-22', 'Arroyo Naranjo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kezilei', 'Rizal', '2015-05-28', 'Nikolayevskaya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nangkasari', 'La Esperanza', '2015-06-23', 'Estefania');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Al Miftāḩ', 'San Antonio', '2015-03-30', 'Chambly');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Los Angeles', 'Barlinek', '2015-08-02', 'Kallíthiron');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pueblo Nuevo', 'Porangaba', '2015-08-21', 'Sadabe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('El Copé', 'Ḏânan', '2015-07-01', 'Luti');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dashahe', 'Guararapes', '2015-10-12', 'Almeirim');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Duiwelskloof', 'Tianmen', '2015-02-04', 'Merklín');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Miguel Pereira', 'Mendeleyevskiy', '2015-04-20', 'Shahkot');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Huambalpa', 'Cikuray', '2015-09-09', 'Bolgar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Retiro', 'Tetovo', '2016-02-02', 'Kyustendil');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bibirevo', 'Lac du Bonnet', '2016-01-04', 'Ribeirão Preto');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bohus', 'Na Klang', '2015-04-22', 'Melaka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mikstat', 'Kota Kinabalu', '2015-09-27', 'Hartford');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mymensingh', 'Kunčina', '2015-08-25', 'Siluman');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chengyue', 'Yahil’nytsya', '2015-05-27', 'Yelenendorf');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Libice nad Cidlinou', 'Bela-Bela', '2015-09-13', 'Mvuma');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Haparanda', 'Fruitvale', '2015-12-02', 'Sigeng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guararema', 'Dongsheng', '2015-11-01', 'Guaratuba');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guangming', 'Marabahan', '2015-05-05', 'Sanjinquan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ad Dujayl', 'Moste', '2015-09-27', 'Fonte da Vaca');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Slavyanovo', 'Češinovo', '2015-07-19', 'Yaopi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Krosno', 'Sélestat', '2015-04-24', 'Kiili');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ourtzagh', 'Takeo', '2015-06-29', 'Karanglincak');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Klakeh', 'San Antonio', '2015-02-12', 'Xieshui');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sarnia', 'Zabłocie', '2015-04-15', 'Malpique');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kolodeznyy', 'Charlotte', '2015-04-28', 'Jingzhou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Campo Mourão', 'Barra', '2016-01-13', 'Nevers');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Valledupar', 'Kodamachō-kodamaminami', '2015-08-05', 'San Ramon');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Geldrop', 'Xanxerê', '2015-04-21', 'Yangjiang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jagodnjak', 'Nice', '2015-11-06', 'Hengdong Chengguanzhen');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Almaguer', 'Potlot', '2015-03-19', 'Nan’an');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kawage', 'La Jagua de Ibirico', '2015-03-12', 'Jeberos');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ribeiro', 'Tours', '2015-10-30', 'Perpignan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sikasso', 'Cibogo', '2015-06-05', 'Datong');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dulag', 'Bayan', '2015-06-30', 'Yanglinshi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nytva', 'Tambulatana', '2015-11-06', 'Uyuni');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guoyuan', 'Izyum', '2016-02-02', 'Toulouse');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Liminka', 'Caicun', '2015-02-11', 'Marija Bistrica');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Des Moines', 'Panay', '2015-11-11', 'Bakersfield');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Novi Karlovci', 'Dalubian', '2015-10-17', 'Jugezhuang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Babo-Pangulo', 'Szczaniec', '2015-12-21', 'Concórdia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San Antonio', 'Trondheim', '2015-11-03', 'Gbarnga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('The Valley', 'Pimbalayan', '2015-08-26', 'Blumenau');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Longfengshan', 'Lille', '2016-02-01', 'Diamantina');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Takaoka', 'Katumba', '2015-06-28', 'Lluchubamba');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yangping', 'Jawa', '2015-05-17', 'Patrída');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiaze', 'Idi Rayeuk', '2015-07-10', 'Daying');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Brak', 'Kasimov', '2015-09-25', 'Presidente Bernardes');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Elat', 'Boluo', '2015-04-29', 'Otuzco');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bayt Dajan', 'Ḩurayḑah', '2015-03-10', 'Minamata');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mabini', 'Tríkala', '2015-11-03', 'Thiers');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Napierville', 'Lanxi', '2015-08-08', 'Youhua');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Donghuang', 'Orodara', '2015-10-24', 'Dehī');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dazu', 'Ishige', '2015-08-30', 'Radoboj');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Alpūrai', 'Tajao', '2015-10-20', 'Napenay');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zheleznogorsk', 'Seremban', '2015-10-05', 'Mabuhay');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chelbasskaya', 'Cinyawang', '2015-03-27', 'Longsheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Uiasa', 'Sebba', '2015-03-26', 'Gowarczów');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gaoqiao', 'Wenchang', '2015-09-08', 'Comodoro Rivadavia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('El Cafetal', 'Guadalupe', '2015-10-24', 'Banamba');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Quito', 'Ráječko', '2015-07-18', 'Qunsheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Minanga Norte', 'Beo', '2015-08-18', 'Hamada');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Belanting', 'Pa Tio', '2015-04-20', 'Babat');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Huanshi', 'La Mesa', '2015-09-25', 'Bataiporã');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Omsk', 'Grande Rivière Noire', '2015-08-14', 'New York City');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Garden Grove', 'Najin', '2015-03-23', 'Zaječar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Melbourne', 'Krasnoye', '2015-06-06', 'Changshan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Santa Rita', 'Dallas', '2015-10-23', 'Nyahururu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lahad Datu', 'Cibulakan', '2015-04-21', 'Goim');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Concepción', 'Hejiaping', '2015-09-17', 'Sanankerto');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Faranah', 'Songjianghe', '2015-02-25', 'Damatou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xujiaqiao', 'Tubungan', '2015-10-16', 'Gamleby');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yanjiang', 'Mpika', '2015-09-26', 'Pará de Minas');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jianshan', 'Siemiątkowo', '2015-11-05', 'Maikun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Utan', 'Sritanjung', '2015-07-13', 'Wuxiang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Łęki Szlacheckie', 'Tours', '2015-10-06', 'Bianxiong');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tsowkêy', 'Cileunyi', '2015-02-09', 'Osoyoos');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jincheng', 'Nürnberg', '2015-08-09', 'Canoas');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Serravalle', 'Ōzu', '2015-04-28', 'Xuhang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pinggan', 'Jiantianjie', '2015-12-11', 'Manakara');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pembuanghulu', 'Phumĭ Véal Srê', '2015-09-01', 'Chengnan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pingshanhu', 'Tongjiang', '2016-01-01', 'Tempursari Wetan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mentaraman Satu', 'Kuty', '2015-11-26', 'Wujiayao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Prochnookopskaya', 'Bordeaux', '2015-02-23', 'Grabów');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Farmahīn', 'Barong', '2015-07-25', 'Gangtun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jianfeng', 'Xingzi', '2015-09-24', 'Kolochava');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Normandin', 'Ké-Macina', '2015-09-19', 'Tianxingchang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bąków', 'Souillac', '2015-06-03', 'Kými');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pellegrini', 'Vällingby', '2015-08-02', 'Al Muţayrifī');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Baru', 'Cigembor', '2015-07-31', 'Luruaco');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Uherské Hradiště', 'Nakonde', '2015-07-17', 'Vellinge');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ninomiya', 'Augusto Corrêa', '2015-11-10', 'Pohbango');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dadong', 'Kargowa', '2015-04-12', 'Embarcación');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Calibishie', 'Glazov', '2015-10-13', 'Iset’');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhongyuanlu', 'Palmira', '2015-07-13', 'Hrušovany u Brna');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tonglin', 'Nusajaya', '2015-04-03', 'Conselheiro Lafaiete');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Welchman Hall', 'San Rafael', '2015-10-06', 'Huangtan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ţubarjal', 'Caruaru', '2015-09-29', 'Pršovce');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tuanlin', 'Parychy', '2015-06-17', 'Morrison');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Al Qubbah', 'Kruševo', '2015-09-05', 'Thị Trấn Tân Yên');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Obong', 'Chemerivtsi', '2015-08-06', 'Facatativá');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Minuyan', 'Tucson', '2015-05-09', 'Prochnookopskaya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tampakan', 'Plateliai', '2015-08-26', 'Qīr Moāv');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jönköping', 'Kose', '2015-07-26', 'Vila Verde');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('New York City', 'Xiaoduchuan', '2015-07-14', 'Châu Thành');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Blagoveshchensk', 'Sinilian First', '2015-11-17', 'Rychtal');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bunisari', 'Lubbock', '2015-09-30', 'Banjar Bucu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Vulcan', 'Dengteke', '2015-02-03', 'Fier');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chuguyevka', 'Ajuda', '2015-08-24', 'Ordzhonikidzevskaya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dadianzi', 'Phanom Sarakham', '2015-06-30', 'Tukan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Siraway', 'Altan-Ovoo', '2015-05-28', 'Burbank');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shah Alam', 'Tietê', '2015-10-29', 'Santa Rosa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Liuge', 'Nancaicun', '2015-03-09', 'Anthoúsa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Banjar Dauhmargi', 'Bochum', '2015-02-14', 'Xieqiao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wŏnju', 'Ostrzeszów', '2015-06-01', 'San Andrés');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Criciúma', 'Ust-Kamenogorsk', '2016-01-16', 'Wako');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Słupsk', 'Libertador General San Martín', '2015-12-21', 'Babao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Viligili', 'Marseille', '2015-06-22', 'Vicente Guerrero');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mopipi', 'Desakolot', '2015-11-13', 'Klole');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sumberkindagan', 'Cô Tô', '2016-01-19', 'Kongolo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Widorokandang', 'Las Lomas', '2015-07-03', 'Desa Nasol');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Valinhos', 'Las Vegas', '2015-08-03', 'Jām Sāhib');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Maroúsi', 'Savonranta', '2015-11-22', 'Lidong');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kuching', 'Bin’an', '2015-02-25', 'Komatsu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lorut', 'Khust', '2016-01-31', 'Bachok');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San José', 'Ruangwa', '2015-08-13', 'San Ramón');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Texistepeque', 'Toktogul', '2015-07-31', 'Richards Bay');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bakıxanov', 'Kodyma', '2015-07-19', 'Gradići');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pengbu', 'Pasrukrajan Satu', '2015-12-27', 'Mikhaylovka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Libertad', 'Nizami', '2015-12-27', 'Awka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Asopía', 'Bogotá', '2015-02-09', 'Novhorod-Sivers’kyy');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Phú Thái', 'Xinzhou', '2015-12-05', 'Lyon');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guanghai', 'Luoxiong', '2015-06-27', 'Mudian');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tejar', 'Turgun', '2015-12-21', 'Bollnäs');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pākpattan', 'Margasari', '2015-03-02', 'San Sebastián de Yalí');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Newark', 'Khamyāb', '2016-01-20', 'Avellaneda');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Doksy', 'La Cueva', '2015-05-24', 'Sarilhos Grandes');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Leiden', 'Arcoverde', '2015-09-27', 'Tushi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Regente Feijó', 'Sanjwāl', '2015-05-10', 'Qiaolin');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sanchang', 'Vale de Santarém', '2015-11-01', 'Casimiro de Abreu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Opatov', 'Langue', '2015-02-25', 'Telč');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Baiqi', 'Donja Mahala', '2016-02-02', 'Bŭka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sabbah', 'Candi Prambanan', '2015-12-06', 'Shanga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lavaltrie', 'Seaforth', '2015-03-30', 'Klapagading');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ifanadiana', 'Noisy-le-Grand', '2015-05-09', 'Udomlya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Klyuchevsk', 'Al Bāţinah', '2015-03-30', 'Sukoreno');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kawanoechō', 'Wysoka', '2016-01-25', 'Beauvais');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pasacao', 'Demak', '2015-04-14', 'Kamubheka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wudong', 'Jivia', '2015-10-22', 'Shushary');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Villejuif', 'Osapsio', '2015-11-07', 'Thị Trấn Tam Điệp');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Salvacion', 'Shucheng Chengguanzhen', '2015-02-14', 'Reading');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Cakungsari', 'Keruguya', '2015-03-12', 'Xiwei');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Borik', 'Banho e Carvalhosa', '2015-12-09', 'Shangping');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nacimiento', 'Kalangan', '2015-04-09', 'Santander');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Stutterheim', 'Shangganshan', '2015-11-06', 'Huddinge');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shenwan', 'Verkhnevilyuysk', '2015-04-17', 'Terjan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kugri', 'Antipolo', '2015-12-21', 'Catalina');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhili', 'Cikijing', '2015-09-14', 'Komarno');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Saniwonorejo', 'Balayang', '2015-04-11', 'Kasui');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chengtang', 'Barrancas', '2015-02-15', 'Funehikimachi-funehiki');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bluefields', 'Purral', '2015-10-17', 'Leuweheq');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sulangan', 'Magoúla', '2016-01-20', 'Bayshint');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hastings', 'Balangpule', '2015-11-16', 'Renhe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ljusdal', 'Perpignan', '2015-04-02', 'Chicama');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wanliang', 'Okayama-shi', '2015-07-28', 'Nyíregyháza');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yongchang', 'Maradi', '2015-07-11', 'Ráquira');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Billings', 'Shīeli', '2016-02-02', 'Dubăsari');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Topeka', 'Ngã Bảy', '2015-09-16', 'Nashville');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Huangcun', 'Oslo', '2015-07-28', 'Salvacion');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhujiang', 'Bendo', '2015-09-28', 'Kabaty');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Algeciras', 'San Sebastián', '2016-01-03', 'Zwolle');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Boro Utara', 'Cabungan', '2015-05-08', 'Finspång');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhengyangshan', 'Shengmi', '2015-10-12', 'Slantsy');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Talalora', 'Muzaffargarh', '2015-12-16', 'Rivadavia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sherwood Park', 'Phu Kradueng', '2015-04-17', 'Fort-de-France');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mayskiy', 'Chavarría', '2015-06-28', 'Hongguang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Champagnole', 'Dongjian', '2015-10-16', 'Dogarmo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Maagnas', 'Zakliczyn', '2015-04-11', 'Kalinkavichy');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Brejo Santo', 'Gaobu', '2015-12-31', 'Quinta');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lyubokhna', 'Huangqiao', '2015-07-20', 'Jalqamūs');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ar Ruways', 'Ždánice', '2015-08-12', 'Saint-Étienne-du-Rouvray');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gornje Živinice', 'Pondokrejo Wetan', '2015-05-12', 'Isla Pucú');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Leiwang', 'Tyoply Stan', '2015-03-12', 'Danzi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sighnaghi', 'Jinbo', '2015-07-06', 'Svedala');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Asaka', 'Duwakbuter', '2015-04-08', 'Jiaozuo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xichang', 'Laâyoune / El Aaiún', '2015-03-01', 'Lallayug');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Aghajari', 'Kroonstad', '2015-11-21', 'Dante Delgado');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Profítis Ilías', 'Damnica', '2015-12-09', 'Titab');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kandangan', 'Varoška Rijeka', '2015-03-12', 'Kortowo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Birobidzhan', 'Maluno Sur', '2015-07-11', 'Pedreira');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lidingö', 'Alderetes', '2015-02-16', 'Charlotte Amalie');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Cipanjang', 'Masoyila', '2015-09-11', 'Kuźnia Raciborska');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Saint-Quentin', 'Qingtaiping', '2016-01-12', 'Mae Ramat');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Novopokrovka', 'Longzui', '2015-10-11', 'Sheffield');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Camabatela', 'San Julian', '2015-04-23', 'Ransiki');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San Andres', 'Quintas', '2015-07-15', 'Ganjun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ronneby', 'Miami', '2015-09-04', 'New York City');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Narita', 'Pondokaso', '2015-03-18', 'Santa Venera');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dasiping', 'Ribeiro', '2015-09-22', 'Ampelákia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jargalant', 'Miyako', '2015-07-18', 'Sugihan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Krasnyy Klyuch', 'Jiuxian', '2015-04-01', 'Sausa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Whittier', 'Kanshan', '2015-03-05', 'Czarna Dąbrówka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yamada', 'Tabanan', '2016-01-21', 'Entradas');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dongshentou', 'Belén de Umbría', '2015-11-03', 'Enonkoski');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shaxi', 'Longka', '2015-04-25', 'Sarnów');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Janów', 'Changqi', '2015-02-21', 'Wanga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pasirputih', 'Pochep', '2015-12-08', 'Nysa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kthella e Epërme', 'Nyanza', '2015-02-21', 'Vetluga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Krajan Sidodadi', 'Vila Nova', '2015-12-19', 'Gushan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Grand Forks', 'Kobylanka', '2015-07-02', 'Wutun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Parigi', 'Gengcheng', '2015-12-05', 'Mzuzu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sagbayan', 'Göteborg', '2015-11-01', 'Brikama');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dehui', 'Nangela', '2015-04-19', 'Sernancelhe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dmitriyevskoye', 'Ţubarjal', '2015-09-25', 'Acton Vale');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Baquero Norte', 'Mugan', '2015-11-01', 'Oroqen Zizhiqi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Samagaltay', 'Al Ḩarf', '2015-03-23', 'Rijeka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Filothéi', 'Anding', '2015-04-18', 'Santa Iria de Azóia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhaojia', 'Iida', '2015-12-25', 'Rongcheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('La Concepcion', 'Znamenka', '2016-01-20', 'Yuwang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bugarama', 'Huanggang', '2015-04-27', 'Kobylí');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Altares', 'Siquisique', '2015-03-25', 'Hezhi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Norsborg', 'Tocoa', '2015-07-12', 'Bidyā');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jaru', 'Jankovec', '2015-08-13', 'Sidi Slimane');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kedungbacin', 'Quimper', '2015-02-17', 'Berezayka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kertosari', 'Dār an Naşr', '2015-03-15', 'Ancol');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kiełczów', 'Barranca de Upía', '2015-10-25', 'La Cruz');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Odeleite', 'Chancay', '2015-07-04', 'Castlerea');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Laslovo', 'Galatás', '2015-08-30', 'Capulaan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sindangsari', 'Tongchuan', '2016-01-07', 'Oyo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Riversdale', 'Jilili', '2015-03-21', 'Puger');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wurno', 'Arraial do Cabo', '2016-01-20', 'Kalutara');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Piltown', 'Shiren', '2016-01-03', 'Carbonear');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sapporo', 'Ayaviri', '2016-01-09', 'Vanves');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Puerto Cumarebo', 'Qingshandi', '2015-03-05', 'Krajan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hazlov', 'Halmstad', '2015-11-13', 'Al Qurayn');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tuba', 'Sumberjeruk', '2015-07-03', 'Laval');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tanggungrejo', 'Minggang', '2015-07-06', 'Krajan Demit');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Campurrejo', 'Ganding', '2015-02-27', 'Krokeaí');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Coroatá', 'Kněžpole', '2015-11-02', 'Maralal');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pangguang', 'Montluel', '2015-11-28', 'Jinzhou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiangkouxu', 'Bairro Assunção Piedade', '2015-02-23', 'Sabnova');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Palma De Mallorca', 'Kokubu-matsuki', '2016-01-07', 'Penghu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ħamrun', 'Chornorudka', '2015-05-31', 'Balaklava');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Vargas', 'Wurno', '2015-09-09', 'Tamana');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Alannay', 'Karangpeton', '2016-01-24', 'Yuekou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ufa', 'Yangdian', '2016-01-21', 'Virginia Beach');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Reno', 'San Ramón', '2015-12-11', 'Sierpc');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yuktae-dong', 'Hengqiao', '2015-08-02', 'Karabudakhkent');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Smołdzino', 'Profítis Ilías', '2015-11-23', 'Nakanojōmachi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Selouane', 'Orange', '2015-10-21', 'Jinka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yonghe', 'Medvedok', '2015-09-28', 'Barretos');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Dokolo', 'Sibulan', '2015-12-04', 'Dobryanka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Colendra', 'Besuk Selatan', '2015-03-30', 'Orlovskiy');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Oguma', 'Shanggan', '2016-01-27', 'Sucre');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ledoy', 'Prokop’yevsk', '2015-06-09', 'Foz do Iguaçu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Aranitas', 'Sapouy', '2015-06-02', 'Fuchang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mapaniqui', 'Enskede', '2015-06-02', 'Uvarovka');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pejibaye', 'Isakly', '2015-07-03', 'Ban Dan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hexing', 'Akune', '2015-12-07', 'Lengkongbarang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Palos', 'Mosteiro', '2015-11-12', 'Przywidz');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Laozhuang', 'Binabaan', '2015-04-21', 'Panineungan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Amieira', 'Aleksinac', '2016-01-27', 'Xin’an');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Qinā', 'Chayuan', '2015-12-31', 'Marigot');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tall Abyaḑ', 'Omoa', '2016-01-27', 'Sepekov');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ḩurayḑah', '20 de Noviembre', '2015-11-26', 'Zhuanqiang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guofu', 'Al Finţās', '2015-05-11', 'Lobuk');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Coruripe', 'Sulitair', '2015-12-30', 'Waterloo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lihu', 'Xiaolou', '2015-10-30', 'Yolöten');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jilong', 'Las Higueras', '2015-10-30', 'Novo Selo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Přibyslav', 'Sobreda', '2015-02-12', 'Żebbuġ');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bangxi', 'Neuzina', '2015-05-30', 'Clisson');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Berovo', 'Compiègne', '2015-09-21', 'Ansheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lons-le-Saunier', 'Huaminglou', '2015-09-04', 'Al Ghandūrah');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Al Manāqil', 'Borovichi', '2015-04-23', 'Daqin Tal');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gongli', 'Waru Selatan', '2015-04-01', 'Taquari');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Rosthern', 'Heerlen', '2015-06-17', 'Bilje');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tyshkivka', 'Bromma', '2015-07-01', 'Horodnytsya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tuy Phước', 'Youghal', '2015-03-29', 'Skovorodino');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sanjiangkou', 'Émponas', '2015-10-06', 'Chikwawa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('General Elizardo Aquino', 'Baguim do Monte', '2015-02-09', 'Kyperoúnta');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Příšovice', 'Mendez-Nuñez', '2015-12-18', 'Qal‘at al Andalus');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Namangan Shahri', 'Zákynthos', '2015-05-31', 'Baimaqiao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mojo', 'Guangshan Chengguanzhen', '2015-06-07', 'Butembo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiangshan', 'Bilohirs’k', '2016-01-27', 'Nanyi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Padaran', 'Asopía', '2015-12-29', 'Nanxiang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gaohu', 'Ibiá', '2015-12-28', 'Pechenga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Awsīm', 'Yuzhno-Sukhokumsk', '2015-06-09', 'Siraway');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Klang', 'Bergville', '2015-09-08', 'Palaiochóri');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pallisa', 'Carregal', '2015-04-04', 'Balesari');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ilo', 'Patayac', '2015-02-25', 'Bamut');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Carepa', 'Yakymivka', '2015-03-30', 'San Luis');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shawnee Mission', 'Hanbin', '2015-12-05', 'Ożarowice');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hämeenkoski', 'Mlanggeng', '2015-08-09', 'Granadero Baigorria');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ţūbās', 'Chuantang', '2015-02-28', 'Runović');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('São Sebastião', 'Cikaung', '2015-11-19', 'Getafe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Miejsce Piastowe', 'Ngora', '2015-04-08', 'Sundbyberg');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Rincón', 'Shunling', '2015-11-01', 'Eqlīd');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ono', 'Curvelo', '2015-10-19', 'Seraya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kishkenekol’', 'Ternovka', '2015-12-01', 'Kirawsk');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Makur', 'Hongqi', '2015-05-23', 'Mojorembun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kuala Terengganu', 'Xipingle', '2016-01-01', 'Ayrihuanca');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San Vicente', 'Loujiadian', '2015-11-22', 'Beichengqu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tomobe', 'Azenha', '2015-09-16', 'Vittel');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ritaebang', 'La Charité-sur-Loire', '2016-01-14', 'San Miguel');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Skien', 'Akim Swedru', '2015-12-06', 'Midland');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Binzhou', 'Manhuaçu', '2015-09-18', 'Portumna');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Changning', 'Skorogoszcz', '2015-02-15', 'Tatebayashi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Chaiyo', 'Tubod', '2015-09-13', 'Kayunga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hainan', 'Proletarsk', '2015-08-03', 'Monroe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Takarazuka', 'Bantog', '2015-08-03', 'Okocim');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Purranque', 'Balangpule', '2015-12-10', 'Esuk Oron');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Calgary', 'Nowe Warpno', '2015-11-24', 'Drochia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Żabnica', 'Tangchi', '2015-05-06', 'Yayao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Malpique', 'Potikosin', '2015-03-26', 'Ganyi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yangxunqiao', 'Portalegre', '2015-08-01', 'Batken');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kalapagenep', 'Jince', '2015-08-17', 'Mazańcowice');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Vukatanë', 'Anastácio', '2015-07-04', 'Farroupilha');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Créteil', 'Arenal', '2015-04-19', 'Tulungrejo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Varberg', 'Magumeri', '2015-10-16', 'Bāfq');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Laval', 'Puubheto', '2015-05-18', 'Gaojimiao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Folques', 'Yehud', '2015-10-28', 'Dębów');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shi’an', 'Knoxville', '2015-04-03', 'Yangmingbu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Boroko', 'Kalamangog', '2015-11-19', 'Tianxingchang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Songbai', 'Tucurú', '2016-01-06', 'Bryan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Naberera', 'Pato-o', '2015-02-09', 'Margaharja');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sarangmeduro', 'Jiaxing', '2015-04-03', 'Huangascar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Karasgede', 'Kahama', '2015-04-16', 'Igoumenítsa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Oral', 'Dadiharja', '2015-06-10', 'Ribeira Quente');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Colorado Springs', 'Bakungan', '2016-01-24', 'Nanga Eboko');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xiema', 'Härnösand', '2015-08-22', 'Kansas City');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Torre', 'Solec-Zdrój', '2015-03-19', 'Yinhedahan’er');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gavinhos de Baixo', 'Fernando Gutierrez Barrios', '2015-09-10', 'Shijiazhai');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Waco', 'Fruitvale', '2015-06-09', 'Pitalito');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Banjar Brahmanabukit', 'Bang Lamung', '2015-04-07', 'Bamusso');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('El Espino', 'Jiangchuan', '2015-08-22', 'Colonia Elisa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Karpogory', 'Nawal', '2015-11-01', 'Nancheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Carlos Casares', 'Drakino', '2015-06-16', 'Baojia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Skogås', 'Klisura', '2015-04-04', 'Shah Alam');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiedu', 'Sagasa', '2015-07-17', 'Serang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Alfenas', 'Phrae', '2015-08-03', 'Issoire');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Karolinka', 'Burnham', '2015-04-14', 'Ichuña');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sieradza', 'Damai', '2015-04-10', 'La Rioja');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guangshan', 'Pitomača', '2015-03-05', 'Gamping Lor');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Täby', 'Olszanica', '2015-06-27', 'Moengo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sempol', 'Tecka', '2015-02-16', 'Nässjö');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Salamnunggal', 'Juai', '2016-01-08', 'Luopioinen');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Beizhakou', 'Tacoma', '2015-11-02', 'Trunovskoye');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Songgai', 'Kuta', '2016-01-12', 'Tingsiqiao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Souto', 'Horní Jelení', '2016-01-20', 'Zhanxu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Berthierville', 'Volodarsk', '2015-03-07', 'Quận Tân Phú');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiufeng', 'Marantao', '2015-02-20', 'Gombangan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pasiripis', 'Nieszawa', '2015-03-15', 'Wiślica');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Krueng Luak', 'Seia', '2015-02-26', 'Carcar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bogale', 'Xinzhou', '2015-07-25', 'Fastiv');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Salta', 'Monsanto', '2016-01-14', 'Nowy Korczyn');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Syrskoye', 'Uralets', '2015-12-05', 'Eling');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nevers', 'Yanshi', '2015-12-04', 'Sirari');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tengjia', 'Griboyedov', '2015-09-11', 'Payxambabazar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Calarcá', 'Constanza', '2015-08-03', 'Storvik');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jatisari', 'Suizhong', '2015-09-05', 'Cane');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Santa Ana', 'Chrást', '2015-02-08', 'Sóc Trăng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lyubashivka', 'Arys', '2015-08-21', 'Tsibulev');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Brzyska', 'Oslo', '2016-01-07', 'Lecheng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Blagodatnoye', 'Sindangsari', '2016-01-06', 'Káto Asítai');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Šardice', 'Lemahputih', '2015-12-04', 'Santa Cristina Couto');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Santa Cruz', 'Mari', '2015-10-04', 'Shuitai');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Khelyulya', 'Velká Bystřice', '2015-12-08', 'Redcliff');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shalinskoye', 'Nova Olímpia', '2015-11-15', 'Itacoatiara');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Idrija', 'Novoselitsa', '2015-06-07', 'Slawharad');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lacroix-Saint-Ouen', 'St. Anton an der Jeßnitz', '2016-01-10', 'Nymburk');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ntoum', 'Tagbina', '2015-05-15', 'Fengmen');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gort', 'Kota Bharu', '2015-03-09', 'Melgar');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xieqiao', 'Taotang', '2015-03-17', 'Soisy-sous-Montmorency');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Nahariya', 'Polkowice', '2015-08-17', 'Gongjiahe');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kosiv', 'Payapa', '2015-12-07', 'Hangzhou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('São Gonçalo do Amarante', 'Ngreco', '2015-09-21', 'Martensville');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bagalangit', 'Néa Ionía', '2015-02-12', 'Kungsör');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Matanog', 'Myitkyina', '2015-07-08', 'Sari');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Thawi Watthana', 'Lenchwe Le Tau', '2015-10-14', 'Aotou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Laweueng', 'Escuintla', '2015-02-04', 'Aragarças');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ndago', 'Jammāl', '2016-01-28', 'Oštarije');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lucapon', 'Xiaxi', '2015-06-06', 'Bograd');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sakchu-ŭp', 'Mat-i', '2015-08-26', 'Ibaiti');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pélla', 'Trollhättan', '2015-05-24', 'Reutov');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guantou', 'São Miguel do Iguaçu', '2015-03-15', 'Libao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Awgu', 'Pangian', '2015-11-25', 'Purac');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sukatani', 'Hägersten', '2015-07-17', 'Goght’');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bromma', 'Strasbourg', '2015-05-20', 'Eirol');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sujiatun', 'Lampa', '2016-01-28', 'Kamaishi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Angus', 'Novovarshavka', '2016-01-08', 'Pushkino');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Wang Thonglang', 'Blahodatne', '2015-02-14', 'Suba');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yutsa', 'Portela', '2015-12-31', 'Batangtoru');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Datun', 'Tucson', '2015-07-13', 'Toulon');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Komarno', 'Plewiska', '2015-04-01', 'Benito Juarez');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Puhja', 'Awarawar', '2015-07-13', 'Sidenreng');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bielawy', 'Lipin Bor', '2015-10-06', 'Richmond');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gouxaria', 'Krasnohrad', '2015-11-01', 'Taraban Timur');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Hollola', 'Canguaretama', '2015-12-25', 'Tygda');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Drammen', 'Sarilhos Grandes', '2015-02-04', 'Nanling');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Żabno', 'Itaberaba', '2015-12-31', 'Orikhiv');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Cilangkap', 'Mała Wieś', '2015-06-05', 'Banjar Kajanan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Białobrzegi', 'Kajok', '2015-06-24', 'Milot');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Narsingdi', 'Shatalovo', '2015-06-09', 'Pevek');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiepai', 'Yuchi', '2015-08-24', 'Valle de La Pascua');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pogorzyce', 'Huicungo', '2015-02-15', 'Krivyanskaya');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Esmeralda', 'Tabasalu', '2015-09-23', 'Maoqitun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tournon-sur-Rhône', 'Dolní Počernice', '2016-01-05', 'Sinilian First');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Diriamba', 'Taikang', '2015-04-06', 'Bauan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xiajiashan', 'Shūkat aş Şūfī', '2015-03-24', 'Ystad');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Xipi', 'Wanglu Kulon', '2015-03-03', 'Dome');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lyon', 'Jincheng', '2015-03-25', 'Heling');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Fujieda', 'Jieguanting', '2015-12-19', 'Cereté');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Milltown', 'Susoh', '2015-10-02', 'Shekou');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Zhaozhen', 'Vodstroy', '2015-05-22', 'Teresa');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Cucutilla', 'Tayturka', '2015-02-03', 'Auki');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Buaran', 'Sapu Padidu', '2015-06-22', 'Tingsiqiao');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San Jos', 'Pulau Pinang', '2015-09-19', 'Sŭngho 1-tong');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Al Qurḩ', 'Cilolohan', '2015-03-24', 'Brétigny-sur-Orge');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bieliny', 'Nankāna Sāhib', '2015-12-21', 'Shibushi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pringgabaya', 'Zavet', '2016-01-11', 'Guanting');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tía Juana', 'Xichehe', '2015-09-19', 'Wang Thonglang');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Palaiomonástiron', 'Kalangala', '2015-09-04', 'Amuñgan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Shtip', 'Unión', '2015-04-26', 'Saint-Nazaire');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Bogo', 'Niono', '2015-02-07', 'Žebrák');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Qingshuitang', 'Shipka', '2015-11-10', 'Basiong');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guayabo Dulce', 'Lerum', '2015-06-17', 'El Carmen');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Beo', 'Gaoqiao', '2015-11-13', 'Maba');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yayao', 'Bayabas', '2015-09-24', 'Baoxu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kamiennik', 'Paphos', '2016-01-27', 'San Marcos');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Yunxian Chengguanzhen', 'Lembang', '2015-07-04', 'Kota Kinabalu');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guadalupe Victoria', 'Wagini', '2015-07-01', 'Buenos Aires');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kolochava', 'Kintinku', '2015-02-24', 'Zhongxing');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Kebonjaya', 'Otyń', '2015-06-09', 'Baro');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Huancheng', 'Ash Shiḩr', '2015-08-21', 'Qiling');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Karangasem', 'Katrineholm', '2015-09-07', 'Pasirtujuhpuluh');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mutum Biyu', 'Oytal', '2015-02-07', 'Buraen');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pictou', 'Fleury-les-Aubrais', '2015-09-05', 'Dinājpur');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Sua', 'Xianrendu', '2015-08-21', 'Liuzhi');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Radzyń Chełmiński', 'Tekik Wetan', '2016-01-01', 'Wanjia');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Spartanburg', 'Banjarsari', '2015-10-28', 'N''Djamena');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mathakola', 'Chornukhyne', '2015-08-03', 'Santa María Ixhuatán');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Oleksandriya', 'Tanjungbatu', '2015-12-06', 'Infanta');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Rapas', 'Delft', '2015-09-27', 'Makueni');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tocoa', 'Zapolyarnyy', '2015-08-01', 'Tonosí');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ayacucho', 'Entre Rios', '2016-01-24', 'Valinhos');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Vsetín', 'Ballsh', '2015-06-12', 'Daxing');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Pedinó', 'Los Aquijes', '2015-09-30', 'El Cairo');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Butahai', 'Kastrat', '2015-04-20', 'Macroom');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Guiyang', 'Rivera', '2015-04-03', 'Majagual');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Tyresö', 'Liaobu', '2015-02-10', 'Qinlan');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Roma', 'Benito Juarez', '2015-05-04', 'Avdzaga');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Periyiáli', 'Konstantinovo', '2015-11-25', 'Padaimut');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Lederaba', 'Wenchang', '2015-09-13', 'Nanmuping');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Mori', 'Taoxi', '2015-05-13', 'Pulangbato');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Ningzhong', 'Kamalaputi', '2015-09-17', 'Cheping');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Jiuxian', 'Knurów', '2015-11-12', 'Podujeva');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Gresik', 'Tupanciretã', '2015-09-17', 'Kalvola');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Stockholm', 'Don Tan', '2015-07-15', 'To’rtko’l Shahri');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Oslo', 'Shengli', '2015-05-16', 'Dakoutun');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('‘Uqayribāt', 'Tiflet', '2015-09-02', 'Malinovoye Ozero');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('Fengxian', 'Lewoeleng', '2015-09-09', 'Palkovice');
insert into configurazione (co_nome, co_valore, co_data, co_descrizione) values ('San Isidro', 'South River', '2015-09-22', 'Kuvshinovo');
